version: '3'
services:

  nginx:
    image: scheduraphycontainer.azurecr.io/nginx:latest
    depends_on:
      - bot
      - liff
      - web

  bot:
    image: scheduraphycontainer.azurecr.io/bot:latest
  liff:
    image: scheduraphycontainer.azurecr.io/liff:latest
  web:
    image: scheduraphycontainer.azurecr.io/web:latest
