version: '3'
services:

  bot:
    image: scheduraphycontainer.azurecr.io/bot:latest
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./bot:/app

  web:
    image: scheduraphycontainer.azurecr.io/web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    depends_on:
      - bot
