version: '3'
services:

  bot:
    image: scheduraphycontainer.azurecr.io/bot:latest
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./bot:/app

  liff:
    image: scheduraphycontainer.azurecr.io/liff:latest
    build:
      context: ./liff
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./liff:/app
    depends_on:
      - bot
