version: '3'
services:

  nginx:
    image: scheduraphycontainer.azurecr.io/nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx:/usr/share/nginx/html
    depends_on:
      - bot
      - liff
      - web

  bot:
    image: scheduraphycontainer.azurecr.io/bot:latest
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./bot:/app

  liff:
    image: scheduraphycontainer.azurecr.io/liff:latest
    build:
      context: ./liff
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./liff:/app

  web:
    image: scheduraphycontainer.azurecr.io/web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
